### PR TITLE
Tested on Raspbian Stretch in Raspberry 3B+

### PR DESCRIPTION
**Pull request by rdelcorro**
Updated the Readme to include the Raspberry 3B+ with internal wifi and stock Raspbian Stretch

### CODE REVIEW

**Comment by Bennedetto** [comment]
I just tested on Raspberry 3B+ - and failed. No device (Android, Windows, IOS) can detect to the wifi "vtrust-flash". I flashed the linked image and left everything to stock.
So sadly I can verify, that this does NOT work on a Raspberry 3B+ and the linked kali image .

**Comment by rdelcorro** [comment]
I did not use the attached image but rather the official Raspbian stretch. Note that the PR references that software version. I can send screenshots. I also already flashed 4 devices

**Comment by Bennedetto** [comment]
Sorry, you are absolutely right! Furthermore, I can confirm that stock Raspbian stretch works on a Raspberry 3B+ using this repository to flash generic devices!

**Comment by fsociety999** [comment]
Using on 3B+ with dietpi works perfectly.

**Comment by kueblc** [comment]
Thanks for the confirmation, merged

**Pull request merged**
