### PR TITLE
Fix for #138

### PR DESCRIPTION
**Pull request by PeteLawler**
Python3 from 3.7 on manages pip installs a little differently. This change should handle this change.
*NOTE: I can't recall where I saw that this is the preferred 3.7 method. I can't cite. However things work better now for me. See #138 as well.

### CODE REVIEW

**Comment by pfeerick** [comment]
`bc` will need to be installed @ line 7 as a dependency if used on a virgin raspberry pi system, as it's not installed installed by default. It should be possible to craft a simple detection using python itself... something like this should work:

```
python3 -c 'import sys; exit(1) if sys.version_info.major == 3 and sys.version_info.minor < 7 else exit(0)'
if [ $? -eq 0 ]
then
   sudo pip3 install paho-mqtt pyaes tornado
else
   sudo python3 -m pip install paho-mqtt pyaes tornado
fi
```

**Comment by kueblc** [comment]
Thank you Peters

I do like @pfeerick's dependency free solution.

I think that we should set a variable with the dependencies and use that so additional dependencies will require editing only one line. Something like:

```
PY_DEPENDENCIES="paho-mqtt pyaes tornado"
if python3 -c 'import sys; exit(0) if sys.version_info.major == 3 and sys.version_info.minor < 7 else exit(1)' ;
then
   sudo -H pip3 install $PY_DEPENDENCIES
else
   sudo -H python3 -m pip install $PY_DEPENDENCIES
fi
```

**Comment by kueblc** [comment]
Can anyone say whether using `sudo -H pip3 ...` is ever preferable to `sudo -H python3 -m pip`? Would it work OK to just have the latter?

**Comment by kueblc** [comment]
Included in #331

**Pull request closed without merging**
