### PR TITLE
Warning about Ubuntu 20.04 and later

### PR DESCRIPTION
**Pull request by jcisio**
Notice about incompatibility with Ubuntu 20.04+ https://github.com/ct-Open-Source/tuya-convert/issues/836

### CODE REVIEW

**Comment by kueblc** [comment]
Hi @jcisio thanks for your contribution!

I actually am able to use tuya-convert just fine on my Ubuntu 20.04 machine. The script installs `dnsmasq` during `install_prereq.sh` and checks for `systemd-resolved` during `start_flash.sh`, stopping the service if present.

If there is an issue with this process on your machine, let's try to figure out what's causing it and fix it.

**Comment by jcisio** [comment]
It's strange then. On my PC it said that port 53 was busy and could not install dnsmasq. Some sources say the same thing (but some others don't) when I simply search for "Ubuntu 20.04 dnsmasq":
https://kifarunix.com/configure-local-dns-server-using-dnsmasq-on-ubuntu-20-04/
https://onesys.ch/setup-dnsmasq-on-ubuntu-20-04-lxc/

However I discovered that this tool has a Dockerfile, which uses an Ubuntu 18.04 base image and I tested with it. I'll check later about the installation of dnsmasq on my PC.

**Comment by jcisio** [comment]
Oh I see it now. I should have not stopped there. In `setup_checks.sh` it kills all services listenning to required ports (e.g. 53) and then in `setup_ap.sh` it manually starts dnsmasq. Thus, in `install_prereq.sh` dnsmasq fails to start but it is not a problem.

Thank you for the explanation. I'm closing this PR.

**Comment by kueblc** [comment]
Ah, that makes sense! I already had dnsmasq installed so I wouldn't have seen the error on installation. Thanks for looking into it.

**Pull request closed without merging**
