### PR TITLE
changed docker-image to alpine

### PR DESCRIPTION
**Pull request by Cyber1000**
- alpine might be more lightweigth than a ubuntu-based-container
   - used suggestion from https://github.com/ct-Open-Source/tuya-convert/issues/796, but made some adjustments:
      - don't use alpine:latest, but alpine:3.12, since it's better to use fixed versions
      - some packages where still missing
- updated readme:
   - added some troubleshooting information, like firewall problems: https://github.com/ct-Open-Source/tuya-convert/issues/638
   - or how to get the name of your interface: https://github.com/ct-Open-Source/tuya-convert/issues/793
- since it's not based on  phusion/baseimage-docker anymore bug https://github.com/ct-Open-Source/tuya-convert/issues/840 won't occur again
- In this image I don't separate between building and starting the image, it should be easier to use for the average user. In general I did some cleanup to make usage easier. This was a suggestion in https://github.com/ct-Open-Source/tuya-convert/issues/532#issuecomment-583830883 -> in general https://github.com/ct-Open-Source/tuya-convert/issues/532 shouldn't occur in the future, since I refactored the docker-part.
- Added iproute2 iputils-ping to install_prereq.sh since that is already needed and normally installed on ubuntu/debian, but getting into problems if not

The issues I linked here may be closed after merging, since all relevant info is said and/or problems got fixed

### CODE REVIEW

**Comment by Cyber1000** [comment]
This may also fix (or at least make troubleshooting easier) - whoever had this problems, please check after merging:
- https://github.com/ct-Open-Source/tuya-convert/issues/811
- https://github.com/ct-Open-Source/tuya-convert/issues/900
- https://github.com/ct-Open-Source/tuya-convert/issues/570

**Comment by Cyber1000** [comment]
Note to myself:
- this image should work with podman - testing myself on fedora, if positive PR https://github.com/ct-Open-Source/tuya-convert/pull/732 may be obsolete (@ohadlevy may test this too after merging this PR)
- this PR adds a switch for different OSes: https://github.com/ct-Open-Source/tuya-convert/pull/890 - After this is merged I would add a switch for alpine OS, to get everything for setting up a host or docker into install_prereq.sh. For now the setup is kept within Dockerfile. To make the correct switch-statement: The ID is alpine in /etc/os-release

**Comment by Daveyr** [comment]
This might also fix #922, where I can't use the base image on a Raspberry Pi 4. Alpine supports armv7 so in theory it should run fine.

**Comment by kueblc** [comment]
@Cyber1000 @ohadlevy @aravindkoneru

Thank you all for your contributions! I apologize for the delay getting back to this.

Since I am not at all familiar with Docker, can you please let me know which of #732, #915, #923 is ready for merge and which are obsolete/redundant?

**Comment by Cyber1000** [comment]
Sorry my time was limited too due to heavy work load

#923 -> does exactly the same as this PR (#915), but #915 does a little bit more (especially using alpine as base which can be used on raspberry os too)
#732 -> uses fedora-minimal which won't work on raspberry os. I haven't tested my new docker on fedora (no time/no WLAN-Interface on my fedora machine), so someone may try it. Anyway it it safe to merge #732, it just is an alternative Dockerfile named Dockerfile.fedora, which doesn't get used automatically, you would have to include it in your yml (or overwrite the original Dockerfile) to use it - we may add something to the README if we merge this

**Comment by kueblc** [comment]
Sorry for the delay! Day jobs...

**Pull request merged**
