### PR TITLE
Automatically download latest version of ESPurna and Tasmota during install_prereq.sh

### PR DESCRIPTION
**Pull request by JeffResc**
This pull request introduces the feature of automatically downloading the latest version of `espurna-base-1MB.bin` and `tasmota-wifiman` directly to the `files/` directory (saving them as `espurna.bin` and `tasmota.bin`, respectively). The ESPurna binary is downloaded directly from [their GitHub releases](https://github.com/xoseperez/espurna/releases) while the Tasmota binary are downloaded from [Tasmota's OTA server](http://thehackbox.org/tasmota/). It downloads these using `curl` during `install_prereq.sh` and it does not require any additional dependencies. I've also documented these changes in the README.

If this pull request is accepted, I would also like to add a few more features. One that would check these binaries to ensure they are under 512KB as well as a prompt during `install_prereq.sh` asking the user if they would like to download these files, as not every user wants to download these additional resources.

### CODE REVIEW

**Comment by kueblc** [comment]
Thanks for your PR @JeffResc! I'll take a closer look in a bit.

We do already [check filesize](https://github.com/ct-Open-Source/tuya-convert/blob/31856ada24a1e951b4da849bff2ed056f544c51b/scripts/firmware_picker.sh#L15-L17) by the way.

**Comment by kueblc** [comment]
Hi @JeffResc, I like the idea of offering users the convenience of grabbing the latest version, but I agree it should be optional.

We should leave the included binaries as is, and prompt the user on installation if they would like to update these. This way, if they choose not to update, there are still options that have been tried and tested by many members of the community, giving them the best chances of a successful flash.

**Comment by JeffResc** [comment]
Alright, I can work on that. Is a Y/N prompt to update each of them during install_prereq.sh sound like a good idea. There would be two prompts, one of each firmware.

**Comment by kueblc** [comment]
Sounds great, you can use something similar to [this pattern for y/N prompt](https://github.com/ct-Open-Source/tuya-convert/blob/31856ada24a1e951b4da849bff2ed056f544c51b/scripts/firmware_picker.sh#L53-L55)

**Comment by mcspr** [comment]
Also note of the [nightly releases](https://github.com/mcspr/espurna-nightly-builder/releases) for Espurna, and the rename of -base binary to -core-webui in the current development version

**Comment by digiblur** [comment]
While I do welcome the automation, I would be careful on pulling down the latest dev builds of Tasmota as they are built in an automated fashion and it has happened before where bad bins were created.  Typically not a problem when you are flashing to test devkit boards with USB ports but if a user flashes a bad bin to a light bulb that might be an issue.

**Comment by JeffResc** [comment]
@digiblur I agree, is there any method to verify the integrity of the bin file? Maybe we could pull from GitHub releases in hope those will be tested before uploading (not nightly builds?)

**Pull request closed without merging**
