### PR TITLE
Update intermediate firmware to 1.3

### PR DESCRIPTION
**Pull request by kueblc**
- Improved fail safes during flashing
- Won't erase system params until `flash3` is successful
- Do not reboot if flash failed
- Flash commands now wait to report success or error code rather than responding immediately
- Miscellaneous clean up and refactoring

### CODE REVIEW

**Comment by kueblc** [comment]
Fixes #362 #366 #375

**Comment by mcspr** [comment]
@kueblc hey, sorry to hijack the pr, but i am not sure whether this also fixes the issue that had been reported by the espurna user: https://github.com/xoseperez/espurna/issues/1959
(i have been following the other issues, but i think that is related to the .bin size being larger than the available space?)

The gist of it - flashing properly sized binary with incorrect flash size bit (e.g., 4MB bit written to the 1MB flash chip) will break esp8266/Arduino OTA mechanism. But, for example, flashing with esptool.py will silently replace the bit with the real size, allowing OTA to be used later.

**Comment by kueblc** [comment]
Hi @mcspr,

We check the size of the firmware file itself and reject it if it does not fit the available space, but do not currently check the flash size byte. If the firmware fits but has the incorrect flash mode/size, it may well result in the described issue. I'd be happy to add a check for this in our next milestone.

**Comment by kueblc** [comment]
@mcspr do you know if it would be wise to silently overwrite bytes [2,3) with what's already on the board? Any unexpected side effects of doing so?

**Comment by mcspr** [comment]
None that I am aware of. I tried both espurna and tasmota builds using 4MB flash size, but flashed them manually to the 1MB ESP8285 via esptool.py
Both firmwares upgraded just fine, loosing settings in the process though because of different eeprom sector locations. Any fs would obviously break too between updates.

esptool.py algorithm seems safe, replacing flash size in the config bytes based on the target device's size
https://github.com/esp8266/Arduino/pull/4877 updater already silently keeps the flash mode as-is, but only if built with recent Core versions

**Comment by kueblc** [comment]
@mcspr see https://github.com/vtrust-de/esp8266-ota-flash-convert/pull/8/commits/4b1ef4b43e78efa7aa6182f35213a16554e2fa17. Appreciate the feedback!

**Pull request merged**
