### PR TITLE
Correct Sonoff-Tasmota version in script and readme

### PR DESCRIPTION
**Pull request by pfeerick**
Point to the right version of Sonoff-Tasmota, and mention that it is a custom build, rather than the stock `sonoff-basic.bin` as previously stated. Perhaps the changes from the stock binary should also be pointed out - I for one would like to know what was changed - as I'm still unclear what is different about the binary.

I'd also like to update line 32 of the readme.md to mention Buster as well as Stretch for Rasbian, as it works fine for me, but perhaps some more confirmations first (although I do believe on the new-api PR I saw mention of other Buster users?).

### CODE REVIEW

**Comment by meingraham** [comment]
The version of the firmware binary in the Tuya-Convert package is Tasmota 6.6.0.7.

**Comment by kueblc** [comment]
The firmware was provided by @digiblur via #277 #284. As far as I am aware, it is still a `sonoff-basic` build, just with the WiFi manager option enabled. I'd ask @digiblur for input on this.

**Comment by digiblur** [comment]
Right. It's basically a slimmed down version to fit in this one step flash method much like sonoff basic bin is except with Wi-Fi manager enabled by default to prevent folks from getting locked out of their device due to incompatible passwords or wrongly entered passwords. No core Tasmota functions or code were changed, only commenting out unnecessary features in the user_config.h file. 

It is recommended if they are staying with Tasmota as their firmware that they upgrade to a full build of Tasmota that has many sensors, auto discovery, etc. The OTA process in the firmware upgrade section of Tasmota is a couple clicks away from an upgrade.

**Comment by digiblur** [comment]
Reviewing the commit of this readme is not correct. The only file that is custom is the thirdparty.bin build. The standard one was left for the ones that want to keep things pure.

**Comment by meingraham** [comment]
The "standard" one is 6.6.0.7. Not sure what Tasmota version the "thirdparty" binary that Travis provided is.

**Comment by digiblur** [comment]
It was 6.6.0.7 as well.

**Comment by pfeerick** [comment]
@meingraham The current "standard" / stable / release version is 6.6.0, whereas the current development version is 6.6.0.7. 

Re-reviewing the recent changes to the repo, I didn't realise the thirdparty link had been deleted and a second firmware added - my mistake. Hence, this repo is still shipping 6.5.0 of son-off basic... 

So I'll instead update the binary so that the versions are correct, and add mention that there is a custom version supplied by digiblur to ensure WifiManager is always available, rather than requiring the button to be operable to access it.

**Comment by meingraham** [comment]
@pfeerick 

It is a misconception that 6.6.0 (release) is **_the_** stable version and that minor versions are not. Tasmota has three branches, two are "public". There is the stable master branch (e.g., 6.6.0), the **stable** development branch (e.g., 6.6.0.15), and the _experimental_ branch. The public branches are both stable. In fact, there are known bugs in 6.6.0 that are fixed in the development branch. Not only that, but there are a multitude of new features in the most current branch.

I flashed a couple of devices two days ago. I used `flash3` without any arguments. Does this install `thirdparty.bin` or `sonoff-basic.bin` from the cloned package? The version that was flashed to my devices is 6.6.0.7 (I upgraded immediately afterwards to get the latest features and fixes). My point is, if users clone the Tuya-Convert package, they are going to (may) get 6.6.0.7, not 6.6.0.

Mike

**Comment by pfeerick** [comment]
@meingraham Prior to the latest changes to the repo ten days ago resulting from #277, there was only `sonoff-basic.bin` v6.5.0, and a symbolic link to it called `thirdparty.bin`. Since then, the link has been replaced with a file, meaning by default the custom 6.6.0.7 version is used, and the `sonoff-basic.bin` (6.5.0, although this PR also updates that to 6.6.0) version. So as the PR currently points out, the 6.6.0.7 is used by default, but the sonoff-basic.bin is **_also_** present. 

At no point did I say that the 6.6.0 point releases weren't stable. However, they are **_NOT_** the release versions, and are coming from the development branch. It can't get much simpler than that. For people wanting to tinker, like myself, by all means, use a point release from the development branch... but I will never recommend it out of the box, especially as possibly the first point of contact a person might have with the firmware... There is a [reason](https://github.com/arendst/Sonoff-Tasmota#development) it says on the front of the Tasmota README that it shouldn't be used in production or hard to reach devices - since the non-release version binaries are merely development binaries that successfully compiled.

**Comment by meingraham** [comment]
@pfeerick 

I misunderstood what you meant by this, that's all. I "fixated" on `stable` rather than `release`.
> The current "standard" / stable / release

Just so you are aware, there are a couple of fairly big bugs in 6.6.0. To reduce the potential of being contacted regarding issues, you, as the primary contact for Tuya-Convert, may be better off staying with 6.5.0 if you wish to provide a version labeled `release`.

The recommendation from those of us who deal with Tasmota users on a daily basis is to use the development branch. The statement you referred to from the Tasmota README does not reflect the current reality of how we operate. The development branch really isn't for tinkerers - it is the primary. I think you may see this change in philosophy addressed in the README in the next day or so. Myself and all the Tasmota mods issue the recommendation to install the latest development branch as the very first step... even if the issue being experienced is not related to a known 6.6.0 bug. With the advent of TC v2, we've had a considerable ramp up in users visiting the forum for assistance. First question - `Status 2`... typically immediately followed by the `Upgrade 1` request.

On a note for consistency, perhaps the versions should match whether a user selects `sonoff-basic` or `thirdparty`. If the goal is to provide the version labeled `release`, that should apply regardless of which binary included in the package they choose to use. If they are going to get Travis' (@digiblur) customized firmware, perhaps that ought to also be compiled against the current release branch?

Again, just a recommendation. It is your preference.

Mike

**Comment by pfeerick** [comment]
I'm not the primary contact, just another user (hence the PR ;) ) 

And the case you've just pointed out - major bugs - falls into that exception to the 'generally' rule... meaning either fall back to 6.5.0 or forward to a working point release. ;) I'm surprised there's no 6.6.1 yet if there are fairly big bugs in 6.6.0 as it's been out for a while. 

If the level of support issues encountered has increased since TC v2 does that mean there's a bug in 6.6.0.7 that's causing grief - as that's the version of the binary that was added when it went live? I went the 6.5.0 > 6.6.0 and 6.6.0.7-digiblur -> 6.6.0 paths using the OTA firmware upgrade command with default update URL, and both upgrade paths have worked fine, but that's a small sample (7 of the same device) in one particular network environment. Or have people been swapping in their own binary? 

Either way, point taken, and I certainly wouldn't want to suggest changes that cause unnecessary extra work... What would you suggest is the best version to use atm... 6.5.0? Or a recent point release development build, (but no the most recent one perhaps, since I see there was some mention a few hours ago of a bug in the latest development build)?

**Comment by meingraham** [comment]
No bugs, per se. 6.6.0.7 is better than 6.6.0. Just more users using Tasmota and needing to come up to speed on how to configure and use.

net-net "release" is really just a label of a point in time. The development and QA is exactly the same for release and development.

My recommendation - keep the status quo (6.6.0.7) and just note that in the README.

**Comment by Jason2866** [comment]
Recommended file http://thehackbox.org/tasmota/sonoff-tuya.bin

**Comment by pfeerick** [comment]
I think I will end up closing this PR, and re-doing it from scratch, when the sonoff-wifiman becomes available. In the mean time, I will do another PR in a day or so when I'm actually awake enough to write clearly to add that `reset 5` should be run as part of the configuration stage... i.e. on first run.

**Comment by Jason2866** [comment]
[sonoff-wifiman.bin](http://thehackbox.org/tasmota/sonoff-wifiman.bin)

**Comment by kueblc** [comment]
Thanks again for your hard work @pfeerick. While this is now a bit outdated, hopefully the intent is covered by #396. I'd be happy to get your feedback there.

**Pull request closed without merging**
