### PR TITLE
Delete Tasmota binaries

### PR DESCRIPTION
**Pull request by Jason2866**
Solves #335 

To be 100% clear this is a official request from the maintainers of Tasmota.
Dont include Tasmota bin files without a warning.

Tasmota NEEDS a erased flash to work reliable

### CODE REVIEW

**Comment by kueblc** [comment]
I thought you wanted to update the bin, not remove it

**Comment by Jason2866** [comment]
No we cant submit a Tasmota firmware which works with Tuya Convert in its current version.
Tasmota needs a erased flash to work correct and reliable.
Tuya Convert doesnt erase flash

**Comment by kueblc** [comment]
It does erase flash before writing. It can not erase flash it's sitting on though, so it only erases the other partition. If started in userspace 1 it will do a full erase. We can look at erasing system params in addition, since that seems to be where your errors in your serial log come from.

**Comment by kueblc** [comment]
I can't just delete these, sorry. At minimum we'd need to symlink thirdparty.bin to espurna and update the README. But it all seems pretty irrational to me, most people are not having problems and there is already advice to use `flash 5`.

**Comment by Jason2866** [comment]
`reset 5` solves issue if device manage to start somehow.... BUT there are devices which never starts!
So we have users on DISCORD which blames Tasmota for bricking there device.
Since Tasmota is designed to have a full erased flash we see At the moment no other choice

**Comment by kueblc** [comment]
I don't have anything personal against you but you seem to be coming at me with a lot of aggression. I hope I am mistaken. Anyway it would be great if you'd like to work with me to track down the issue. Would you share with me a backup that has been corrupted through the process?

**Comment by Jason2866** [comment]
Yes, i am emotional because we have unhappy users in Discord with defect devices, which
cant be opened without destroying (bulbs) and others. Since i dont have personally
any Tuya device i cant help. I submitted the finding already.
I am not agressiv just to prevent more defect devices it is a need to remove the Tasmota binaries

**Comment by Jason2866** [comment]
You can ask @digiblur he did some research and maybe he has some time for

**Comment by Jason2866** [comment]
Afaik Espurna will be no alternative because Espurna stores settings in flash too

**Comment by kueblc** [comment]
OK take a deep breath, we are going to be OK! I have no disrespect for Tasmota, I have even contributed support for a fairly popular module, and I'm sure people will understand when things don't go 100%.

There is explicit warning you must read before using `tuya-convert` that absolves all risk. It is risky and we are not telling users otherwise. However most users are successful, including my own devices.

I'm not sure that removing all binaries from `tuya-convert` is the right answer. What use is it then?

**Comment by kueblc** [comment]
I'll reach out to @digiblur when I can and see if we can work on this together.

**Comment by Jason2866** [comment]
Okay, please work on it with high priority. 
We would be very happy users can use Tuya convert to bring Tasmota safe on there devices!!

**Comment by meingraham** [comment]
@kueblc 

It may be possible for the initial stubs which are flashed during the TC process to perform an erase of the newly empty flash memory address spaces. Some clues here perhaps (credit to @shantur)

https://github.com/vtrust-de/esp8266-ota-flash-convert/blob/master/src/esp8266-ota-flash-convert.ino#L247

**Comment by kueblc** [comment]
@meingraham Yes that is the intention, the problem is you can not erase flash "under your feet" so it can only erase flash which is not running.

Currently it erases user2 from user1, then user1 from user2, but if you start from user2, it will not be fully erased, and cannot be since it is running.

We might be able to erase the system param section (the last 12kb IIRC), which I think may solve the issue since that is what the serial log posted by @Jason2866 seems to show as the problem.

**Comment by meingraham** [comment]
Yes, I understand... can't erase the memory of the code that is running ;-)

Adding that bit to erase the parameter area to the TC process would be a good step. Basically, any flash that can be erased outside of the currently running segment.

**Comment by kueblc** [comment]
I can't reproduce the issue on my devices, so while I am happy to make the change and build a new intermediate, I can't test that it actually fixes the issue. Can you or any users you know test the fix once I build it?

**Comment by meingraham** [comment]
We can enlist some folks (@digiblur cough cough) to assist.

**Comment by Jason2866** [comment]
Sure! as @meingraham  wrote

**Comment by digiblur** [comment]
I can test it with a switch that I have the stock Tuya firmware that I have taken back and forth several times. Easy no soldering connection to it.

**Comment by kueblc** [comment]
Latest commit to `development` updates intermediate firmware to erase [244, 256) on `/flash3`. That should cover both Tasmota's settings area and the system params.

**Comment by Jason2866** [comment]
Thx, i already pinged digiblur to test.

**Comment by digiblur** [comment]
I can confirm...  no massive spewing of FF's and such in between reboots.  Used the same switch as yesterday and same procedure.  

image

**Comment by kueblc** [comment]
Excellent, thanks for testing @digiblur and thank you @Jason2866 for bringing the issue to my attention. I'll merge this into `master` right away.

Correct me if I'm wrong, would this make `flash 5` unnecessary now?

**Comment by digiblur** [comment]
``reset 5`` is the command but I'm not 100% sure on it.  It's not a bad thing to do after you get into Tasmota, but that's only my opinion the deal.

**Comment by effelle** [comment]
@kueblc if you erase the sectors a `reset 5` will be more a fail-safe for us but I agree with Travis: 
an extra cleaning will not hurt.  @Jason2866 what do ou think?

**Comment by andrethomas** [comment]
@kueblc 

> Correct me if I'm wrong, would this make reset 5 unnecessary now?

Yes - Tasmota would not really care what is in all the other unused sectors.

The dev bin build scripts have been updated to build the new variant in what would likely be its final name `sonoff-wifiman.bin`

I still need to work through an updated my_user_config.h provided by @digiblur and make sure everything that is not needed is disabled for this binary to keep it < 500k.

Thank you guys for taking the time to make the changes!

**Comment by Jason2866** [comment]
@kueblc  Thank you for your fix!
@digiblur  Thank you for research(es) and testing the fix.

**Comment by meingraham** [comment]
Colin,

I'm not sure what the best way to communicate this to Tuya-Convert users is. An announcement has been posted on the Tasmota Discord. But, for those users that flashed their devices prior to this fix, they need to perform the `Reset 5` before they attempt the first Tasmota OTA firmware update. That is why continuing to recommend this step is appropriate. A Config backup, followed by a `Reset 5`, then the OTA, and finally a configuration restore should be followed. After all, a configuration backup is always recommended. And the time to perform a Reset is just the time of a reboot. In other words, this recommendation is fairly low effort for users.

Cheers!

Mike

**Comment by shantur** [comment]
@kueblc 

Wouldn't it be better to use the wifiman build directly from Tasmota release url (stays same for latest release) instead of adding the binary, this way Tuya-convert users will always get the latest tasmota release.
I believe most of Tuya-convert users are not going to do `git pull` once they have it.

**Comment by andrethomas** [comment]
TC only needs a single working bin which does not have to be the latest version all the time - from there it can be user upgraded if there are some special features in a later version.

**Pull request closed without merging**
