### PR TITLE
Arch Linux support for install_prereq.sh

### PR DESCRIPTION
**Pull request by C0rn3j**
I edited the script to detect OS (and fallback to debian-based install should detection fail) and added a relevant function for Arch Linux (and possibly its derivatives).

I have changed installing the pip modules as current user(root), not system-wide, as that conflicts with the system package manager.

I looked where the pip dependencies are used and it looks like they're all called from `sudo screen`, so installing as root user should be correct.

Tested with Ubuntu 20.10 and Arch.

EDIT: Went through with the flash on Arch successfully, but had to disable NM as it was interfering with the AP script, added note to the setup while I was at it.

### CODE REVIEW

**Comment by jmiahman** [comment]
The Network Manager service is also called NetworkManager on most Red Hat based distributions as well. It would be nice if there was a check for it (ie. check if network-manager or NetworkManager is a running service) to make the script was a tad more dynamic. I have no issues writing it and submitting a PR if that is something that will be accepted.

**Comment by kueblc** [comment]
Hi @C0rn3j, thanks for your contribution! I'll switch the base branch to `development` which is currently staging for the next release.

Regarding NetworkManager @C0rn3j and @jmiahman, this should already be handled automatically. If this is not working then that is an issue unto itself. See the relevant code [here](https://github.com/ct-Open-Source/tuya-convert/blob/94acc3bb020361266ceb74f082e1d25c92a60345/scripts/setup_ap.sh#L27) and let me know how we can improve. I will gladly take a PR for this.

The rest looks good to me, though I'm not able to test comprehensively.

**Comment by C0rn3j** [comment]
Fixed the conflict due to rfkill being added (in util-linux on Arch), hopefully correctly

**Comment by C0rn3j** [comment]
@kueblc 
I fixed the conflict that popped up a while ago, could you please pull this? I did test it when I originally made the commit.

Tried to test it now again but unfortunately it seems that newer version of BW-SHP6 Pro and other devices now do not ship with ESP8266 anymore...

**Comment by Sabin-Gheorghiu** [comment]
Can this be merged?

**Comment by kueblc** [comment]
Thanks for your contribution! I haven't had a chance to test but LGTM so it's now on dev branch

**Comment by C0rn3j** [comment]
Side note, the latest commit can be improved to first try stopping NetworkManager and not network-manager, as network-manager is the old name, so it'd be best to try with the new name first instead to avoid needlessly spamming logs.

Thanks for pulling it!

**Pull request merged**
