### PR TITLE
Update Tasmota firmware variant information

### PR DESCRIPTION
**Pull request by meingraham**

### CODE REVIEW

**Comment by kueblc** [comment]
Hi @meingraham, looks good, could you base this on `development`?

**Comment by meingraham** [comment]
As you are probably painfully aware of :wink:, In the Tasmota realm this move and change at a rapid pace. "Maintenance Release" is the term formerly known as "Development Release". "Maintenance" more accurately reflects what the branch really is.

**Comment by kueblc** [comment]
Slight misunderstanding, I meant that we should merge this PR into our `development` branch instead of `master`. I'm about to merge #490 and would be great to have this included.

**Comment by meingraham** [comment]
Colin - "Resolve conflicts"... I'm not sure how to resolve this. I clicked but then I saw no further action I could take (no edit, not select one or the other, ...). Can you merge my README edits for me? Thx

**Comment by kueblc** [comment]
All set :+1:

**Pull request merged**
