### PR TITLE
Update thirdparty.bin to Tasmota 7.0.0.3

### PR DESCRIPTION
**Pull request by digiblur**
Update thirdparty.bin from tasmota-wifiman.bin 7.0.0.3 - Tested from stock Tuya convert to Tasmota on the WiFi network with a Martin Jerry switch.

### CODE REVIEW

**Comment by SirRedZ** [comment]
Tested and working on TeckinSP20 (test) module. (serial access) flashed via Tuya Convert OTA.
Screenshot_2019-11-06 Tasmota - Main Menu

[-=SrZ=-]

**Comment by kueblc** [comment]
Awesome, just need to update README and start_flash to match

**Comment by kueblc** [comment]
Going to merge and update docs on `development`. Thanks @digiblur and @SirRedZ!

**Comment by digiblur** [comment]
Thanks @kueblc for the catch, I got busy with non-tech stuff after I submitted this

**Pull request merged**
