### PR TITLE
added digiMIN build tag to thirdparty.bin

### PR DESCRIPTION
**Pull request by digiblur**
Since this bin is missing several features like Autodiscovery I wanted it to be easy to spot for support tickets that the user wasn't running the full sonoff.bin version

### CODE REVIEW

**Comment by digiblur** [comment]
Will find a tester or two..

**Comment by kueblc** [comment]
Awesome. Will await confirmation from two or more.

**Comment by pfeerick** [comment]
I've just flashed on this on three of the five Medion S85225s that I was Tasmota-frying(?), and it seems fine. The only reason I didn't put it on all five was I was flashing the second one when I realised the updated file was up ;)

image

I can also report that the latest version of the repo code is working great on a Raspberry Pi 3B+ running a freshly written `2019-07-10-raspbian-buster-lite.img` image. No errors during the pre-req install stage - from pip3 or otherwise. Only needed to install git to start with ;) 

https://pastebin.com/and0KaN5

**Comment by SirRedZ** [comment]
I can confirm this bin file works great! just like expected.


DigiMin Screenshot

Thank you Colin and Digiblur!

[-=SrZ=-]

**Comment by digiblur** [comment]
@pfeerick @sirredz thanks for the tests!

**Pull request merged**
