### PR TITLE
Upgrade tasmota to tasmota-lite.bin v9.2.0

### PR DESCRIPTION
**Pull request by barbudor**
Hi
Please consider merging as keeping a too old version in Tuya convert is increasing the risk of users bricking their device when upgrading to the latest version without following the strict upgrade path.
This time, clean PR.
Thanks

### CODE REVIEW

**Comment by kueblc** [comment]
Hi @barbudor, thanks again for your PR.

Where we left it with https://github.com/ct-Open-Source/tuya-convert/pull/854#issuecomment-742921233, I had hoped to get confirmation that this build did not cause any issues when used with tuya-convert. I certainly don't want anyone bricking devices.

If you are reasonably certain that this build is indeed stable, I'm happy to move it along.

**Comment by barbudor** [comment]
Hi @kueblc 
The team was pretty confident in releasing v9.2.0
However if you want an additional safety level, using v9.1.0 would still be better than the current version as the upgrade from 9.1.0 to 9.2.0 would be seamless for users
http://ota.tasmota.com/tasmota/release-9.1.0/tasmota-lite.bin
Many thanks

**Comment by niziak** [comment]
I just flashed 4x Gosund SP111 with tasmota-lite v9.2.0 without any problems.

**Comment by kueblc** [comment]
Great, thanks for testing!

**Pull request merged**
